### ISSUE TITLE
Requirements File

### ISSUE THREAD

**Issue by drlycan** [mbevilacqua/appcompatprocessor#13]
The actual command syntax for the requirements.txt file is:
pip install -r requirements.txt

the install was missing in the README text. More of a whoops than and issue. Also be sure to update/upgrade to 9.0.3 documentation/2.7/user guide 9.0.3

**Comment by mbevilacqua** [comment]
Thanks, addressed on 284f78c64c216331506ef99b180c537246a5f684.

**Comment by drlycan** [comment]
YW........
