### ISSUE TITLE
autopoint

### ISSUE THREAD

**Issue by drlycan** [mbevilacqua/appcompatprocessor#14]
How do we overcome the autopoint error thrown?

You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 volatility-profiles : Depends: volatility but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution)

Is this a bug or context missing as in the install section of the first part of the README.txt?

**Comment by mbevilacqua** [comment]
If you provide details of the platform you are attempting to install in I
might be able to help out.

**Comment by mbevilacqua** [comment]
Wait, what does volatility have to do with this? :)

**Comment by drlycan** [comment]
I was using an old version of SIFT volatility was colliding with the program. So I installed the new SIFT and now I have installed autopoint successfully and now I am getting this error here: $ ./autogen.sh
Unable to find autotools
so in following instruction "B" ./autogen.sh when executed throws the | unable to find autotools error.

**Comment by mbevilacqua** [comment]
don't think this has anything to do with ACP, else please clarify why you think it is related.

**Comment by drlycan** [comment]
So in following the git clone steps listed: 

-Option B Direct from source

    git clone https://github.com/libyal/libregf.git
    cd libregf/
    ./synclibs.sh
    ./autogen.sh <<<< I end up stuck here asking for autopoint from the last sift/ this sift just gives me and error stating cannot find?>>>><<<Cannot move to below processes>>>>
    ./configure --enable-python && make
    sudo make install
    python setup.py build
    python setup.py install

The rest of the requirements you can handle with 'pip install -r requirements.txt'.

**Comment by mbevilacqua** [comment]
Ohhh ok now I see your issue here.
The thing is, if you're installing in SIFT then you should not need to do this as it already has libregf and the python binding installed!

I just downloaded a fresh SIFT VM and got it all working with simply 'sudo pip install -r requirements.txt'.
Let me know if that works for you.

**Comment by drlycan** [comment]
this is what I initially tried then tried to option B when this did not work. I will tear this down and try from scratch cause I am getting a new error now.:
$ sudo pip install -r requirements.txt
The directory '/home/sansforensics/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sansforensics/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by drlycan** [comment]
Successfully installed pip-9.0.3

**Comment by drlycan** [comment]
don't know why I am running into so many issues with this, killing me smalls.........

**Comment by drlycan** [comment]
@root : | root@siftworkstation -> /h/sansforensics 
# pip install -r requirement.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirement.txt'
root@siftworkstation -> /h/sansforensics 
# sudo pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
root@siftworkstation -> /h/sansforensics 
# pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by mbevilacqua** [comment]
Libregf is a royal pain to install.
But I just downloaded a fresh SIFT VM and 'sudo pip install -r requirements.txt' was all that was needed there. Let me know if that works for you.

**Comment by drlycan** [comment]
cool will do not going to screw with this anymore

**Comment by drlycan** [comment]
you know henrik out of sweden?

**Comment by drlycan** [comment]
So new SIFT VM same issues???>>>>>
OSError: [Errno 13] Permission denied: '/usr/bin/pip'
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
sansforensics@siftworkstation -> ~ 
$ sudo pip install --upgrade pip
The directory '/home/sansforensics/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sansforensics/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/
    100% |████████████████████████████████| 1.4MB 4.3MB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-9.0.3
sansforensics@siftworkstation -> ~ 
$ sudo pip install -r requirements.txt
The directory '/home/sansforensics/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sansforensics/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
sansforensics@siftworkstation -> ~ 
$ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
sansforensics@siftworkstation -> ~ 
$ sudo su
root@siftworkstation -> /h/sansforensics 
# pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
root@siftworkstation -> /h/sansforensics 
#

**Comment by drlycan** [comment]
This is what was needed I think so far trying it now. : sudo apt-get install libmysqlclient-dev

**Comment by drlycan** [comment]
done complete that was it on my VM problem solved.
