### ISSUE TITLE
Shimcache hive parser

### ISSUE THREAD

**Issue by nwf9** [mbevilacqua/appcompatprocessor#16]
Hi Matias,

I think it's more useful to modify your naming convention for the shimcache and enable the insensitive case rather than strictly use "SYSTEM" on capital letter.

**Comment by mbevilacqua** [comment]
Are you referring to this snippet here and is the request to maintain the actual naming convention but make it case insensitive?

https://github.com/mbevilacqua/appcompatprocessor/blob/46ba76a73fcf71640f2a6e9db02afaaac3e178b9/Ingest/appcompat_raw_hive.py#L11-L18

**Comment by nwf9** [comment]
Yes that’s exactly what i mean.

**Comment by mbevilacqua** [comment]
554b1377ccf290a319b9d75655274894af995d11 should fix it.
